package main.models.environment.refractors.glasses.lens;

import main.math.algebra.Vector2;
import main.math.shapes.polygons.Polygon;
import main.models.environment.refractors.Refractor;
import main.physics.colliders.PolygonCollider;
import main.physics.optics.Medium;

/**
      Base class for all lens types.

     <p>When extending this class, the subclass must define its own
     static createShape() & calculateArcAngle() methods to generate the Polygon representing
     its lens geometry.</p>
*/
public abstract class Lens extends Refractor {
     protected final float radiusOfCurvature;
     protected final float centerThickness;
     protected final float arcAngle;

     // Constructors

     /**
          @param lensShape the Polygon generated by this lens's static createShape() method
          @param arcAngle the angle of the arcs forming the faces of the lens (custom or generated by len's own calculateArcAngle() method)
     */
     public Lens(Vector2 position, Polygon lensShape, float radiusOfCurvature, float centerThickness, float arcAngle, float rotation) {
          super(
               position,
               new PolygonCollider(position, lensShape, rotation),
               Medium.DENSE_FLINT_GLASS,
               lensShape
          );

          this.radiusOfCurvature = radiusOfCurvature;
          this.centerThickness = centerThickness;
          this.arcAngle = arcAngle;
     }

     /**
          @param lensShape the Polygon generated by this lens's static createShape() method
          @param arcAngle the angle of the arcs forming the faces of the lens (custom or generated by len's own calculateArcAngle() method)
     */
     public Lens(float x, float y, Polygon lensShape, float radiusOfCurvature, float centerThickness, float arcAngle, float rotation) {
          Vector2 position = new Vector2(x, y);
          
          super(
               position,
               new PolygonCollider(position, lensShape, rotation),
               Medium.DENSE_FLINT_GLASS,
               lensShape
          );

          this.centerThickness = centerThickness;
          this.radiusOfCurvature = radiusOfCurvature;
          this.arcAngle = arcAngle;
     }

     // Getters
     public float getRadiusOfCurvature() {
          return this.radiusOfCurvature;
     }

     public float getCenterThickness() {
          return this.centerThickness;
     }

     public abstract Vector2 getLeftFaceCenterOfCurvature();
     public abstract Vector2 getRightFaceCenterOfCurvature();

     /**
          Creates the required lens shape.
          
          @param radiusOfCurvature the radius of curvature of the lens
          @param centerThickness the thickness of the lens
          @return the Polygon representing the lens shape
     */
     protected static Polygon createShape(float radiusOfCurvature, float centerThickness) {
          throw new UnsupportedOperationException(
               "Lens subclass must define its own static createShape() method."
          );
     }

     /**
          Calculates the required arc angle for the lens surface.
          
          @param radiusOfCurvature the radius of curvature of the lens
          @param centerThickness the thickness of the lens
          @return The angle of the arc (minor angle)
     */
     protected static float calculateArcAngle(float radiusOfCurvature, float centerThickness) {
          throw new UnsupportedOperationException(
               "Lens subclass must define its own static calculateArcAngle() method."
          );
     }
}